receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  otlphttp:
    endpoint: https://example.com
    sending_queue:
      enabled: false

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlphttp]
